export default {
  validInput1: {
    firstName: 'Bruce',
    lastName: 'Banner',
    otherName: 'Hulk',
    email: 'banner@yahoo.com',
    password: 'bruce banner',
    phonenumber: '9567483087',
    passportUrl: 'bruce.png',
  },
  validInput2: {
    firstName: 'Mike',
    lastName: 'Owen',
    email: 'mk@yahoo.com',
    password: 'ulor mike',
    otherName: 'Bro',
    phonenumber: '9567483017',
    passportUrl: 'Mike.png',
  },

  existingEmail: {
    firstName: 'Barry',
    lastName: 'Allen',
    email: 'banner@yahoo.com',
    password: 'theFlash',
    otherName: 'Bro',
    phonenumber: '9567483011',
    passportUrl: 'Barry.png',
  },
  incompleteData: {
    firstName: 'Anna',
    lastName: 'Jones',
    email: 'annie@yahoo.com',
  },
  emptyData: {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    otherName: '',
    phonenumber: '',
    passportUrl: '',
  },
  improperData: {
    firstName: '23BruceBanner',
    lastName: '1Jones',
    email: 'banner@yahoo.com',
    password: 'bruce banner',
    otherName: 'Bro',
    phonenumber: 'a567483017',
    passportUrl: 'Mike',
  },
  userOneLogin: { email: 'banner@yahoo.com', password: 'bruce banner' },
  userTwoLogin: { email: 'mk@yahoo.com', password: 'ulor mike' },
  adminLogin: { email: 'pascal@andela.com', password: '12345' },
  emptyLoginData: { email: '', password: '' },
  noEmail: { email: '', password: 'bruce banner' },
  noPassword: { email: 'mk@yahoo.com', password: '' },
  invalidEmail: { email: 'wrongEmail', password: 'bruce banner' },
  invalidPassword: { email: 'Bruce Banner', password: 'wrongPassword' },
  invalidEmailPassword: { email: 'wrongEmail', password: 'wrongPassword' },
};

